//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ForeignWords.App.Resources.Texts {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class HomeResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal HomeResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ForeignWords.App.Resources.Texts.HomeResources", typeof(HomeResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add New Word.
        /// </summary>
        public static string Add_New_Word_Button_Content {
            get {
                return ResourceManager.GetString("Add_New_Word_Button_Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All.
        /// </summary>
        public static string All_New_Passed_Selection_All {
            get {
                return ResourceManager.GetString("All_New_Passed_Selection_All", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New.
        /// </summary>
        public static string All_New_Passed_Selection_New {
            get {
                return ResourceManager.GetString("All_New_Passed_Selection_New", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Passed.
        /// </summary>
        public static string All_New_Passed_Selection_Passed {
            get {
                return ResourceManager.GetString("All_New_Passed_Selection_Passed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to English.
        /// </summary>
        public static string Domestic_Foreign_Selection_Domestic {
            get {
                return ResourceManager.GetString("Domestic_Foreign_Selection_Domestic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Slovak.
        /// </summary>
        public static string Domestic_Foreign_Selection_Foreign {
            get {
                return ResourceManager.GetString("Domestic_Foreign_Selection_Foreign", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to I didn&apos;t know (D).
        /// </summary>
        public static string I_Did_Know_Button_Content {
            get {
                return ResourceManager.GetString("I_Did_Know_Button_Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to I don&apos;t know (N).
        /// </summary>
        public static string I_Do_Not_Know_Button_Content {
            get {
                return ResourceManager.GetString("I_Do_Not_Know_Button_Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to I know (K).
        /// </summary>
        public static string I_Know_Button_Content {
            get {
                return ResourceManager.GetString("I_Know_Button_Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Random Word (R).
        /// </summary>
        public static string Random_Word_Button_Content {
            get {
                return ResourceManager.GetString("Random_Word_Button_Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Refresh.
        /// </summary>
        public static string Refresh_Button_Content {
            get {
                return ResourceManager.GetString("Refresh_Button_Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Transaltion (T).
        /// </summary>
        public static string Translation_Button_Content {
            get {
                return ResourceManager.GetString("Translation_Button_Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Words:.
        /// </summary>
        public static string Words_Count_Label {
            get {
                return ResourceManager.GetString("Words_Count_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Words language:.
        /// </summary>
        public static string Words_Language_Label {
            get {
                return ResourceManager.GetString("Words_Language_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Words List.
        /// </summary>
        public static string Words_List_Button_Content {
            get {
                return ResourceManager.GetString("Words_List_Button_Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Words type:.
        /// </summary>
        public static string Words_Type_Label {
            get {
                return ResourceManager.GetString("Words_Type_Label", resourceCulture);
            }
        }
    }
}
