//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ForeignWords.App.Resources.Texts {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class WordsListResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal WordsListResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ForeignWords.App.Resources.Texts.WordsListResources", typeof(WordsListResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string Cancel_Button_Content {
            get {
                return ResourceManager.GetString("Cancel_Button_Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        public static string Delete_Button_Content {
            get {
                return ResourceManager.GetString("Delete_Button_Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to English Word.
        /// </summary>
        public static string Domestic_Word_Grid_View_Header {
            get {
                return ResourceManager.GetString("Domestic_Word_Grid_View_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit.
        /// </summary>
        public static string Edit_Button_Content {
            get {
                return ResourceManager.GetString("Edit_Button_Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Filter:.
        /// </summary>
        public static string Filter_Label_Content {
            get {
                return ResourceManager.GetString("Filter_Label_Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Score.
        /// </summary>
        public static string Score_Grid_View_Header {
            get {
                return ResourceManager.GetString("Score_Grid_View_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Translations.
        /// </summary>
        public static string Translations_Grid_View_Header {
            get {
                return ResourceManager.GetString("Translations_Grid_View_Header", resourceCulture);
            }
        }
    }
}
